version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
    build: # runs not using Workflows must have a `build` job as entry point
        working_directory: ~/tcup-client # directory where steps will run
        docker: # run the steps with Docker
            - image: circleci/node # ...with this image as the primary container; this is where all `steps` will run
        steps: # a collection of executable commands
            - checkout # special step to check out source code to working directory
            - restore_cache: # special step to restore the dependency cache
                  # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: npm-install
                  command: npm install
            - save_cache: # special step to save the dependency cache
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run: # run tests
                  name: test
                  command: npm test
            - run:
                  name: make-code-coverage-dir
                  command: mkdir .nyc_output
            - run: # run coverage report
                  name: code-coverage
                  command: './node_modules/.bin/nyc report --reporter=text-summary --reporter=text'
