export const topResults = () => ({
    classes: [
        {
            id: 'kombi',
            name: 'Kombi',
            results: [
                {
                    position: 1,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    points: 4021,
                },
                {
                    position: 2,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    points: 3650,
                },
                {
                    position: 3,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    points: 3551,
                },
            ],
        },
        {
            id: 'klub',
            name: 'Klub',
            results: [
                {
                    position: 1,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    points: 4021,
                },
                {
                    position: 2,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    points: 3650,
                },
                {
                    position: 3,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    points: 3551,
                },
            ],
        },
    ],
})

export const totalResults = () => ({
    classes: [
        {
            id: 'kombi',
            name: 'Kombi',
            results: [
                {
                    position: 1,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 4021,
                },
                {
                    position: 2,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3650,
                },
                {
                    position: 3,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3551,
                },
                {
                    position: 4,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3400,
                },
                {
                    position: 5,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3202,
                },
                {
                    position: 6,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3200,
                },
                {
                    position: 7,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3150,
                },
                {
                    position: 8,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3120,
                },
                {
                    position: 9,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 2000,
                },
                {
                    position: 1,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 4021,
                },
                {
                    position: 2,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3650,
                },
                {
                    position: 3,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3551,
                },
                {
                    position: 4,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3400,
                },
                {
                    position: 5,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3202,
                },
                {
                    position: 6,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3200,
                },
                {
                    position: 7,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3150,
                },
                {
                    position: 8,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3120,
                },
                {
                    position: 9,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 2000,
                },
                {
                    position: 1,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 4021,
                },
                {
                    position: 2,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3650,
                },
                {
                    position: 3,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3551,
                },
                {
                    position: 4,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3400,
                },
                {
                    position: 5,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3202,
                },
                {
                    position: 6,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3200,
                },
                {
                    position: 7,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3150,
                },
                {
                    position: 8,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3120,
                },
                {
                    position: 9,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 2000,
                },
                {
                    position: 1,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 4021,
                },
                {
                    position: 2,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3650,
                },
                {
                    position: 3,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3551,
                },
                {
                    position: 4,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3400,
                },
                {
                    position: 5,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3202,
                },
                {
                    position: 6,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3200,
                },
                {
                    position: 7,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3150,
                },
                {
                    position: 8,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3120,
                },
                {
                    position: 9,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 2000,
                },
            ],
        },
        {
            id: 'klub',
            name: 'Klub',
            results: [
                {
                    position: 1,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 4021,
                },
                {
                    position: 2,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3650,
                },
                {
                    position: 3,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3551,
                },
                {
                    position: 4,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3400,
                },
                {
                    position: 5,
                    gainedPosition: 0,
                    startNumber: 'NB',
                    name: 'Vratislav Sram',
                    aeroclub: 'Broumov',
                    glider: 'Nimbus 2M',
                    handicap: 100,
                    points: 3202,
                },
                {
                    position: 6,
                    gainedPosition: 0,
                    startNumber: 'ZS',
                    name: 'Marek Blatak',
                    aeroclub: 'Sumperk',
                    glider: 'Duo Discus T',
                    handicap: 100,
                    points: 3200,
                },
                {
                    position: 7,
                    gainedPosition: 0,
                    startNumber: 'GO',
                    name: 'Ondrej Dupal',
                    aeroclub: 'GAC Benešov',
                    glider: 'ASG 29 18m',
                    handicap: 100,
                    points: 3150,
                },
            ],
        },
    ],
})

export const dailyResults = () => ({
    classes: [
        {
            id: 'kombi',
            name: 'Kombi',
            days: [
                {
                    id: '1',
                    name: 'Den 1',
                    date: '2020-07-11',
                    results: [
                        {
                            position: 1,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: 6574571641,
                            points: 1000,
                        },
                        {
                            position: 2,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: 6574571657,
                            points: 970,
                        },
                        {
                            position: 3,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: 6574571640,
                            points: 930,
                        },
                        {
                            position: 4,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 850,
                        },
                        {
                            position: 5,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 830,
                        },
                        {
                            position: 6,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: null,
                            points: 800,
                        },
                        {
                            position: 7,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 790,
                        },
                        {
                            position: 8,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 750,
                        },
                        {
                            position: 9,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: null,
                            points: 645,
                        },
                    ],
                },
                {
                    id: '2',
                    name: 'Den 2',
                    date: '2020-07-12',
                    results: [
                        {
                            position: 1,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 1000,
                        },
                        {
                            position: 2,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 970,
                        },
                        {
                            position: 3,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: null,
                            points: 930,
                        },
                        {
                            position: 4,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 850,
                        },
                        {
                            position: 5,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 830,
                        },
                        {
                            position: 6,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: null,
                            points: 800,
                        },
                    ],
                },
            ],
        },
        {
            id: 'klub',
            name: 'Klub',
            days: [
                {
                    id: '1',
                    name: 'Den 1',
                    date: '2020-07-11',
                    results: [
                        {
                            position: 1,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 1000,
                        },
                        {
                            position: 2,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 970,
                        },
                        {
                            position: 3,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: null,
                            points: 930,
                        },
                        {
                            position: 4,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 850,
                        },
                        {
                            position: 5,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 830,
                        },
                        {
                            position: 6,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: null,
                            points: 800,
                        },
                        {
                            position: 7,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 790,
                        },
                        {
                            position: 8,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 750,
                        },
                    ],
                },
                {
                    id: '2',
                    name: 'Den 2',
                    date: '2020-07-12',
                    results: [
                        {
                            position: 1,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 1000,
                        },
                        {
                            position: 2,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 970,
                        },
                        {
                            position: 3,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: null,
                            points: 930,
                        },
                        {
                            position: 4,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 850,
                        },
                        {
                            position: 5,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 830,
                        },
                    ],
                },
                {
                    id: '3',
                    name: 'Den 3',
                    date: '2020-07-14',
                    results: [
                        {
                            position: 1,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 1000,
                        },
                        {
                            position: 2,
                            gainedPosition: 0,
                            startNumber: 'NB',
                            name: 'Vratislav Sram',
                            aeroclub: 'Broumov',
                            glider: 'Nimbus 2M',
                            handicap: 100,
                            flightId: null,
                            points: 970,
                        },
                        {
                            position: 3,
                            gainedPosition: 0,
                            startNumber: 'ZS',
                            name: 'Marek Blatak',
                            aeroclub: 'Sumperk',
                            glider: 'Duo Discus T',
                            handicap: 100,
                            flightId: null,
                            points: 930,
                        },
                        {
                            position: 4,
                            gainedPosition: 0,
                            startNumber: 'GO',
                            name: 'Ondrej Dupal',
                            aeroclub: 'GAC Benešov',
                            glider: 'ASG 29 18m',
                            handicap: 100,
                            flightId: null,
                            points: 850,
                        },
                    ],
                },
            ],
        },
    ],
})
