name: CI

on:
    pull_request:
        branches: [master, development]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - run: yarn install
            - run: yarn build
            - run: yarn lint
            - run: yarn format:check
            - run: yarn translations:check
            - run: yarn test

            - name: audit
              run: yarn audit --level high --groups dependencies
