name: deploy-production

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - run: yarn install
            - run: yarn build
            - run: yarn lint
            - run: yarn format:check

    deploy:
        needs: build
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v2
            - run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
            - uses: akhileshns/heroku-deploy@v3.13.15
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: tcup-2025
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
