name: deploy-production

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - run: yarn install
            - run: yarn build
            - run: yarn lint
            - run: yarn format:check
            - run: yarn test

            - name: audit
              run: yarn audit --level high --groups dependencies

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: tcup-2022
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
